---
- name: My Configs for Ubuntu 20.04 on WSL2
  hosts: localhost
  connection: local

  vars:
    fullname: Magnun Leno
    email: magnun.leno@gmail.com
    hostname: vostro-magnun

  tasks:
    - include: tasks/base.yml
      tags: base
    - include: tasks/python.yml
      tags: python
    - include: tasks/development.yml
      tags: development
    - include: tasks/vim.yml
      tags: vim
    - include: tasks/git.yml
      tags: git
