- name: Sets hostname
  hostname:
    name: "{{ hostname }}"
  tags: hostname

- name: Checks if SELinux is enabled
  shell: "grep \"SELINUX=disabled\" /etc/selinux/config"
  ignore_errors: True
  register: selinux

- name: Disable SELinux
  selinux:
    state: disabled
  become: yes
  when: selinux.rc == 1

- name: Disable iptables
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: yes

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: yes

- name: CLI tools
  dnf:
    name:
      - htop
      - httpie
      - lynx
      - ncdu
      - nmap
      - optipng
      - tree
      - xclip
      - youtube-dl
    state: latest
  become: yes

- name: Compressed file formats
  dnf:
    name:
      - cabextract
      - lzip
      - p7zip
      - p7zip-plugins
    state: latest
  become: yes
