- name: Copy WSL config file
  copy:
    src: files/wsl.conf
    dest: /etc/wsl.conf
  become: yes

- name: Copy resolv.conf
  copy:
    src: files/resolv.conf
    dest: /etc/resolv.conf
  become: yes

- name: upgrade all packages
  apt:
    name: "*"
    state: latest
  become: yes

- name: CLI tools
  apt:
    name:
      - htop
      - httpie
      - lynx
      - ncdu
      - nmap
      - optipng
      - tree
      - xclip
      - youtube-dl
    state: latest
  become: yes

- name: Compressed file formats
  apt:
    name:
      - cabextract
      - lzip
      - p7zip
      - p7zip-full
    state: latest
  become: yes
