- name: Dev Tools
  apt:
    name:
      - autoconf
      - automake
      - clang
      - libclang-dev
      - cmake
      - cpp
      - ctags
      - gcc
      - git
      - npm
      - patch
      - silversearcher-ag
      - tmate
      - tmux
      - zsh
    state: latest
  become: yes
