- name: Ensure some GNOME apps are installed
  dnf:
    name:
      - gnome-books
      - gnome-builder
      - gnome-epub-thumbnailer
      - gnome-icon-theme
      - gnome-music
      - gnome-shell-extension-user-theme
      - gnome-themes
      - gnome-tweak-tool
      - dconf-editor
      - gnome-boxes
    state: latest
  become: yes

# Kudos to https://eklitzke.org/lobotomizing-gnome
- name: Remove gnome bloat
  dnf:
    name:
      - evolution
      - evolution-ews
      - evolution-help
      - gfbgraph
      - gnome-contacts
      - gnome-dictionary
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-online-miners
      - gnome-photos
      - gnome-software
      - gnome-user-docs
      - gnome-user-share
      - gnome-video-effects
      - gnome-weather
      - simple-scan
      - totem
      - tracker-miners
      - yelp
    state: absent
  become: yes

- name: ensure core gnome packages are installed
  dnf:
    name:
      - eog
      - evince
      - evolution-data-server
      - flatpak
      - gdm
      - gnome-keyring
      - gnome-menus
      - gnome-screenshot
      - gnome-shell
      - gnome-terminal
      - nautilus
      - redhat-menus
    state: present
  become: yes

- name: mask unwanted gnome services
  systemd:
    name: "{{ item }}"
    user: yes
    masked: yes
    state: stopped
  loop:
    - evolution-addressbook-factory.service
    - evolution-calendar-factory.service
    - evolution-source-registry.service
    - gvfs-goa-volume-monitor.service
    - tracker-store.service

- name: remove tracker databases
  file:
    name: ~/.cache/tracker
    state: absent
  become: yes

- name: Query Gnome-Terminal profile name
  command: 'dconf list /org/gnome/terminal/legacy/profiles:/'
  register: profile

- name: update gnome dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: '/org/gnome/desktop/interface/clock-show-date', value: 'true'}
    - {key: '/org/gnome/desktop/privacy/remove-old-trash-files', value: 'true'}
    - {key: '/org/gnome/desktop/privacy/report-technical-problems', value: 'false'}
    - {key: '/org/gnome/desktop/search-providers/disable-external', value: 'true'}
    - {key: '/org/gnome/desktop/wm/preferences/audible-bell', value: 'false'}
    - {key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled', value: 'true'}
    # - {key: '/org/gnome/settings-daemon/plugins/xsettings/antialiasing', value: "'rgba'"}
    - {key: '/org/gnome/software/allow-updates', value: 'false'}
    - {key: '/org/gnome/software/download-updates', value: 'false'}
    - {key: '/org/gnome/desktop/interface/show-battery-percentage', value: 'true'}
    - {key: '/org/gnome/desktop/wm/preferences/xkb-options', value: "['caps:escape']"}
    - {key: '/org/gnome/desktop/peripherals/touchpad/tap-to-click', value: 'true'}
    - {key: '/org/gnome/terminal/legacy/default-show-menubar', value: 'false'}
    - {key: '/org/gnome/terminal/legacy/default-show-menubar', value: 'false'}
    - {key: "/org/gnome/terminal/legacy/profiles:/{{ profile.stdout.split('\n')[1] }}use-system-font", value: 'false'}
    - {key: "/org/gnome/terminal/legacy/profiles:/{{ profile.stdout.split('\n')[1] }}font", value: "'Inconsolata-dz for Powerline Medium 12'"}
