- name: Python Tools
  dnf:
    name:
      - python3-beautifulsoup4
      - python3-beautifulsoup4
      - python3-coverage
      - python3-devel
      - python3-docutils
      - python3-extras
      - python3-ipdb
      - python3-ipython
      - python3-pip
      - python3-pygments
      - python3-sphinx
      - python3-tkinter
      - python3-unittest2
      - python-coverage
      - python-devel
      - python-docutils
      - python-extras
      - python-ipdb
      - python-ipython
      - python-pygments
      - python-sphinx
      - python-unittest2
      - python-virtualenvwrapper
    state: latest
  become: yes

- name: Installs pip-only packages
  pip:
    name:
      - pipenv
  become: yes
