- name: Python Tools
  apt:
    name:
      - python3-bs4
      - python3-coverage
      - python3-dev
      - python3-docutils
      - python3-extras
      - python3-flake8
      - python3-ipdb
      - python3-ipython
      - python3-jedi
      - python3-pip
      - python3-pygments
      - python3-sphinx
      - python3-unittest2
    state: latest
  become: yes

- name: Installs pip-only packages
  pip:
    name:
      - pipenv
      - isort
      - poetry
  become: yes
